#!/usr/bin/env Rscript

####################################
### load the necessary libraries ###
####################################

suppressPackageStartupMessages(library(optparse))

####################################
#### parse command line options ####
####################################

option_list = list(
    make_option( c("-b", "--bam"), type="character", default=NULL, 
                help="File path to a bam file.",
                metavar="character" ),
    make_option(c("-j", "--junctions"), type="character", default=NULL, 
                help="File path to the junctions file generated by STAR.",
                metavar="character"),
    make_option(c("-a", "--annotation"), type="character", default=NULL,
                help="File path to the annotation file with following format:
binID	gene_id	tx_name	annotated	isIntron
4:3213622-3213736:+	ENSG00000197386	novelExon	N	N
",
                metavar="character"),
    make_option(c("-p", "--pairedEnd"), action = "store_true", default = FALSE,
                help = "Logical indicating whether the data are paired-end [default: FALSE]"),
    make_option(c("-s", "--strandSpecificity"), type="integer", default=0,
                help="A numeric flag indicating whether the data are unstranded [0], strand-specific [1] or reverse strand-specific [2]",
                metavar="integer"),
    make_option(c("-o", "--outputPrefix"), type="character", default=NULL,
                help="A path with a prefix for the output file with counts.",
                metavar="character"),
    make_option(c("-n", "--sampleName"), type="character", default=NULL,
                help="A string with a character name.",
                metavar="character"),
    make_option(c("-r", "--readLength"), type="integer", default=76,
                help="Length of the reads.",
                metavar="integer"),
    make_option(c("-m", "--multipleMapping"), action = "store_true", default = FALSE,
                help = "Logical indicating whether multiple mapping reads should be considered." ))

opt_parser = OptionParser( option_list=option_list )
opt = parse_args(opt_parser)


bamFile <- opt[["bam"]]
junctionFile <- opt[["junctions"]]
annotationFile <- opt[["annotation"]]
sampleName <- opt[["sampleName"]]
outputPrefix <- opt[["outputPrefix"]]
isPairedEnd <- opt[["pairedEnd"]]
strandSpecificity <- opt[["strandSpecificity"]]
readLength <- opt[["readLength"]]
multipleMapping <- opt[["multipleMapping"]]

readLength <- readLength - 8L ## default overhang from regtools and STAR

suppressPackageStartupMessages(library(Rsubread))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(GenomicRanges))

# also requires tidyr & tibble packages

## parses a .jnc file into a nice GRanges object ##
parseJunctionFile <- function(jncFile, strandSpecificity=2){

    juncData <- fread( jncFile )
    data.len <-  nrow(juncData)

    if( ncol(juncData) == 12 ) {
      cat("Junction files seems to come from regtools")

        blockSizes <- strsplit(juncData$V11, ",")
        startBlock <- as.numeric( vapply( blockSizes, function(x){ x[1]}, character(1) ) )
        endBlock <- as.numeric( vapply( blockSizes, function(x){ x[2]}, character(1) ) )
        juncData <- juncData[,c("V1", "V2", "V3", "V4", "V5", "V6")]
        colnames(juncData) <- c("seqnames", "start", "end", "name", "score", "strand")
        juncData$start <- juncData$start + startBlock + 1
        juncData$end <- juncData$end - endBlock
        ## fix rows with undefined strand
        juncData$strand[juncData$strand == "?"] <- "*"
        juncData <- makeGRangesFromDataFrame(
            juncData, seqnames.field="seqnames",
            start.field="start", end.field="end", strand.field="strand", keep.extra.columns=TRUE )
        names( juncData ) <- mcols( juncData )$name

    } else if( ncol( juncData ) == 9 ){
      cat("Junction files seems to come from STAR")
      juncData <- juncData[,c("V1", "V2", "V3", "V4", "V7", "V8")]
      colnames(juncData) <- c("seqnames", "start", "end", "strand", "score", "multScore")
      if( multipleMapping ){
          juncData$score <- juncData$score + juncData$multScore
      }
      juncData$multScore <- NULL
      maxDigits <- nchar(as.character(data.len))
      idTemplate <- paste0("JUN%0.", maxDigits+1, "d")
      juncData$name <- sprintf(idTemplate, seq_len(data.len))
      juncData$strand[juncData$strand == 0] <- "*"
      juncData$strand[juncData$strand == 1] <- "+"
      juncData$strand[juncData$strand == 2] <- "-"
      print(head(juncData))
      juncData <- makeGRangesFromDataFrame(
        juncData, seqnames.field="seqnames",
        start.field="start", end.field="end", strand.field="strand", keep.extra.columns=TRUE )
      names( juncData ) <- mcols( juncData )$name
    }else{
      stop("Junction format not recognized. Are the junction files either
           from the regtools or the STAR output?")
    }
    juncData
}


annotationData <- read.delim( annotationFile )
annotationGRanges <- GRanges( annotationData$binID )
mcols(annotationGRanges) <- DataFrame(annotationData[,c("gene_id", "tx_name", "annotated", "isIntron")] )

exonNumbers <- as.numeric(ave( annotationGRanges$gene_id, annotationGRanges$gene_id, FUN=seq_along ))
annotationGRanges$exonicPartID <- sprintf("E%0.3d", exonNumbers)

names(annotationGRanges) <- paste( mcols(annotationGRanges)$gene_id, mcols(annotationGRanges)$exonicPartID, sep=":" )
rownames(annotationData) <- names(annotationGRanges)

juncData <- parseJunctionFile(junctionFile, strandSpecificity)
juncData <- juncData[strand(juncData) %in% c("+", "-")]
print(head(juncData))
geneRanges <- split( annotationGRanges, mcols( annotationGRanges )$gene_id )
geneRanges <- geneRanges[!grepl("\\+", names(geneRanges))]
geneRanges <- unlist( range(geneRanges) )

ovlJunctionsGenes <- findOverlaps( juncData, geneRanges, type="within", ignore.strand=TRUE )
ovlJunctionsGenes <- split( names(geneRanges)[subjectHits(ovlJunctionsGenes)], names(juncData)[queryHits(ovlJunctionsGenes)] )
ovlJunctionsGenes <- CharacterList(ovlJunctionsGenes)
jMatches <- match(names(juncData), names(ovlJunctionsGenes))
# append dummy element at the end to enable subscription for missing matches
ovlJunctionsGenes <- c(ovlJunctionsGenes, NA)
# fill all missing matches with index of that dummy element
jMatches[is.na(jMatches)] <- length(ovlJunctionsGenes)
geneLists <- ovlJunctionsGenes[jMatches]
mcols(juncData)$genes <- NA
mcols(juncData)$genes <- geneLists


if( strandSpecificity == 0 ){
    ovls <- findOverlaps( annotationGRanges, juncData, type="within", ignore.strand=TRUE )
} else {
    # 1 and 2 strands - forward and reverse
    ovls <- findOverlaps( annotationGRanges, juncData, type="within", ignore.strand=FALSE )
}

junctionGene <- mcols(juncData)$genes[subjectHits(ovls)]
gc()

ovl <- DataFrame(
    queryHits=queryHits(ovls),
    subjectHits=subjectHits(ovls),
    exonID=names(annotationGRanges)[queryHits(ovls)],
    junctionID=names(juncData)[subjectHits(ovls)] )

ovl$junctionGene <- junctionGene

## suuper slow
## ovl <- tidyr::unnest( tibble::as.tibble(as.data.frame( ovl )), cols=c("junctionGene") )
## sum the number of junctions skipping each exon ##
ovlMult <- ovl[lengths(ovl$junctionGene) > 1,]
ovlMult <- tidyr::unnest(as.data.frame(ovlMult), cols=c("junctionGene") )

ovlSingle <- as.data.frame( ovl[lengths(ovl$junctionGene) == 1,] )

ovl <- rbind( ovlSingle, ovlMult )
library(magrittr)

ovl <- ovl %>%
    tidyr::separate( exonID, into=c("geneID", "exonNum"), sep=":" ) %>%
    dplyr::filter( geneID == junctionGene ) %>%
    tidyr::unite( col="exonID", "geneID", "exonNum", sep=":" )

countsPerJunc <- as.data.frame(mcols(juncData)[,c("name", "score")])
colnames(countsPerJunc) <- c("junctionID", "num")

ovl <- dplyr::left_join( ovl, countsPerJunc )
ovl <- ovl %>%
    dplyr::select( exonID, junctionID, num ) %>%
    dplyr::group_by( exonID ) %>%
    dplyr::summarize( num=sum(num) )

gc()
binDF <- data.frame(
    GeneID = names( annotationGRanges ),
    Chr = as.character( seqnames( annotationGRanges ) ),
    Start = start( annotationGRanges ),
    End = end( annotationGRanges ),
    Strand = as.character( strand( annotationGRanges ) ) )

cnts <- featureCounts(
    bamFile,
    annot.ext = binDF,
    isPairedEnd = isPairedEnd,
    countMultiMappingReads = multipleMapping,
    allowMultiOverlap = TRUE,
    strandSpecific = strandSpecificity,
    nthreads = 1 )

gc()
colnames( cnts[[1L]] ) <- sampleName
# print(cnts)
countDf <- cnts[[1]]
colnames(countDf) <- paste0("exoncount_", sampleName)
clName <- paste0("skippingcount_", sampleName)
colnames(ovl)[colnames(ovl) %in% "num"] <- clName

countDf <- countDf %>%
    as.data.frame() %>%
    tibble::rownames_to_column("exonID") %>%
    dplyr::left_join( ovl )
countDf[[clName]] <- ifelse( is.na( countDf[[clName]] ), 0, countDf[[clName]] )

arngs <- annotationGRanges[countDf$exonID]
countDf$binID <- sprintf("%s:%d-%d:%s", as.character(seqnames(arngs)), start(arngs), end(arngs), as.character(strand(arngs))) 

normBin <- pmax(width(annotationGRanges[countDf$exonID]), readLength) / readLength
psiIn <- countDf[[paste0("exoncount_", sampleName)]]/normBin
psiOut <- countDf[[clName]]
psiVal <- psiIn/(psiOut+psiIn)
countDf[[paste0("psi_", sampleName)]] <- psiVal

countDf$exonID <- NULL
countDf <- countDf[,c("binID", paste("exoncount", sampleName, sep="_"), clName, paste0("psi_", sampleName))]
outputFile <- sprintf( sprintf("%s_%s.txt", outputPrefix, sampleName) )

write.table( countDf, file=outputFile, quote=FALSE, sep="\t", col.names=TRUE, row.names=FALSE )
